# Generated by Django 2.2.19 on 2022-09-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220914_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug_url',
            field=models.SlugField(unique=True, verbose_name='Уникальный адрес'),
        ),
    ]
