# Generated by Django 2.2.9 on 2022-10-06 14:35

from django.db import migrations, models

import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221005_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, validators=[posts.validators.validate_not_empty]),
        ),
    ]
