# Generated by Django 2.2.16 on 2022-11-21 10:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Введите текст комментария', verbose_name='Текст комментария'),
        ),
    ]
