# Generated by Django 2.2.16 on 2022-11-23 08:30

import ckeditor.fields
from django.db import migrations
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20221123_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='*Введите текст поста', validators=[posts.validators.validate_not_empty], verbose_name='Текст поста'),
        ),
    ]
