# Generated by Django 2.2.6 on 2022-10-20 18:28

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='*Введите свое имя', max_length=100, validators=[posts.validators.validate_not_empty], verbose_name='Представьтесь, пожалуйста'),
        ),
    ]
